override:
  phpmetrics.coupling.max_afferent: 32
  phpmetrics.coupling.max_efferent: 25
  php.versions: ["8.3", "8.4", "8.5"]
  ci.pr.max_lines_changed: 2000
  ci.piqule_bin: bin/piqule
  sonar.organization: haspadar-org
  sonar.projectKey: haspadar_piqule
  infection.min_msi: 80
  infection.min_covered_msi: 90
  coverage.project.target: 85
  coverage.project.threshold: 1
  coverage.patch.target: 85
  coverage.patch.threshold: 1
  psalm.project.files:
    - "../../bin/piqule"
    - "../../bin/piqule-check"
    - "../../bin/piqule-fix"
    - "../../bin/piqule-sync"
    - "../../bin/piqule-tokens-check"
  phpstan.afferent_coupling.excluded_classes: ['\Haspadar\Piqule\PiquleException']

append:
  infra.exclude:
    - templates
