#!/usr/bin/env sh
set -e

if [ -x "vendor/bin/sheriff" ]; then
  vendor/bin/sheriff check
  exit $?
fi

if command -v composer >/dev/null 2>&1; then
  composer exec -- sheriff check
  exit $?
fi

echo "Sheriff is not installed"
exit 1
