# Hadolint configuration (Sheriff managed)

failure-threshold: {% StringText(hadolint.failure_threshold) %}

ignored: {% StringText(hadolint.ignored_yaml) %}

override:
  error: {% StringText(hadolint.override.error_yaml) %}
  warning: {% StringText(hadolint.override.warning_yaml) %}
