sonar.organization=<< config(sonar.organization)|join(",") >>
sonar.projectKey=<< config(sonar.projectKey)|join(",") >>
sonar.sources=<< config(sonar.sources)|join(",") >>
sonar.tests=<< config(sonar.tests)|join(",") >>
sonar.exclusions=<< config(sonar.exclusions)|join(",") >>
sonar.php.coverage.reportPaths=<< config(sonar.php.coverage.reportPaths)|join(",") >>
