sonar.organization={% StringText(sonar.organization) %}
sonar.projectKey={% StringText(sonar.projectKey) %}
sonar.sources={% ListText(php.src)|Joined(",") %}
sonar.tests={% ListText(php.tests)|Joined(",") %}
sonar.exclusions={% ListText(sonar.exclusions)|Joined(",") %}
sonar.php.coverage.reportPaths={% ListText(sonar.php.coverage.reportPaths)|Joined(",") %}
