# Typos configuration
# Docs: https://github.com/crate-ci/typos

[default]
binary = false
{% ListText(typos.extend_words)|EachFormatted('%1$s = "%1$s"')|Joined("\n")|WhenNotEmpty("\n[default.extend-words]\n%s") %}

[files]
extend-exclude = [
{% ListText(infra.exclude)|EachFormatted("%s/")|EachFormatted('    "%s",')|Joined("\n") %}
]
