coverage:
  status:
    project:
      default:
        target: {% IntText(coverage.project.target)|Formatted("%s%%") %}
        threshold: {% IntText(coverage.project.threshold)|Formatted("%s%%") %}

    patch:
      default:
        target: {% IntText(coverage.patch.target)|Formatted("%s%%") %}
        threshold: {% IntText(coverage.patch.threshold)|Formatted("%s%%") %}

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
